# Generated by Django 4.0.6 on 2022-08-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('line', models.IntegerField()),
                ('shift', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Датчик',
                'verbose_name_plural': 'Датчики',
                'db_table': 'sensor',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.BigIntegerField()),
                ('illumination', models.IntegerField()),
                ('humidity', models.FloatField()),
                ('temperature', models.FloatField()),
                ('date_time', models.DateTimeField(db_column='date_time', null=True)),
            ],
            options={
                'verbose_name': 'Показание',
                'verbose_name_plural': 'Показания',
                'db_table': 'value',
                'ordering': ['id'],
                'managed': False,
            },
        ),
    ]
