# Generated by Django 4.0.6 on 2022-07-25 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentDeviation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'accident_deviation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('point', models.IntegerField()),
                ('array_lines', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'camera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deviations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'deviations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeviationsPlants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'deviations_plants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
            ],
            options={
                'db_table': 'line',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time_1', models.BigIntegerField(blank=True, null=True)),
                ('time_2', models.BigIntegerField(blank=True, null=True)),
                ('time_3', models.BigIntegerField(blank=True, null=True)),
                ('path_1', models.TextField(blank=True, null=True)),
                ('path_2', models.TextField(blank=True, null=True)),
                ('path_3', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pallet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('center', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('line', models.IntegerField()),
                ('shift', models.IntegerField()),
            ],
            options={
                'db_table': 'sensor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypePlant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'type_plant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.BigIntegerField()),
                ('illumination', models.IntegerField()),
                ('humidity', models.FloatField()),
                ('temperature', models.FloatField()),
            ],
            options={
                'db_table': 'value',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
            ],
            options={
                'db_table': 'zone',
                'managed': False,
            },
        ),
    ]
